### ISSUE TITLE
Make AppRegistry typesafe

### ISSUE THREAD

**Issue by mkotsbak** [chandu0101/sri#19]
Replace js.Function, jsArray etc. with actual types.

The types are given here: https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/AppRegistry.js
or in the doc: https://facebook.github.io/react-native/docs/appregistry.html

**Comment by chandu0101** [comment]
@mkotsbak  can you send a PR ?

**Comment by chandu0101** [comment]
by any chance if you know javascript send a PR here https://github.com/facebook/react-native/issues/4380 :D , it will make our life easier :)

**Comment by satya164** [comment]
Hey @mkotsbak, what do you exactly mean? Can you give some more info?

**Comment by chandu0101** [comment]
> mkotsbak - I don't see the need for functional component in Scala. What do you gain over just using a function like this: https://github.com/mkotsbak/Javabin-SriReactNativeDemo/blob/master/mobile/src/main/scala/sri/templates/crossplatform/mobile/AlcoMeter.scala#L26-L30
> I see maybe in JS you get types and default values, but that is not needed in Sri, as you have both types, default values and named parameters:
> See also https://news.ycombinator.com/item?id=10348391

well above issue is not about scala functions vs functional components , while registering if they allow functional components we can pass functions instead of React.createClass with render/React.Component with render  boilerplates as mobile root.

coming to scala methods  vs functional components from HN link you posted u missed main important point 

> in the future, shouldComponentUpdate (or built-in memoization strategy?), you can potentially later change it to be stateful without rewriting consuming code, etc

if you're just using  methods then your component will go bigger and bigger and on state updates react has to diff whole tree ..

**Comment by mkotsbak** [comment]
Ah ok, yes, maybe it is able to optimize on stateless components that has not changed any input properties?

**Comment by mkotsbak** [comment]
But how is this different from pure JS React native? Doesn't they also need to run the AppRegistry function?

**Comment by chandu0101** [comment]
> But how is this different from pure JS React native? Doesn't they also need to run the AppRegistry function?

sorry didn't understand, can you elaborate ...

**Comment by mkotsbak** [comment]
Why did you close it? Is it fixed?

**Comment by chandu0101** [comment]
> Why did you close it? Is it fixed?

I don't know how other open source projects work but  i don't entertain these kind of behaviours in my project.you don't have time to answer my first question/send a two lines of simplePR but you have time to argue on some other unrelated things!. Sorry to be the bad guy In future also i'll do the same thing if its repeated again ,if you don't like it then don't use this project.

**Comment by mkotsbak** [comment]
I might send a PR when I have time to make it, but when the issue is closed it is not encouraging/reminding me or anyone to do it.

I still don't know if the comment https://github.com/chandu0101/sri/issues/19#issuecomment-160133567 is related to this issue or just piggybacked on it.

**Comment by chandu0101** [comment]
> I still don't know if the comment #19 (comment) is related to this issue or just piggybacked on it

i already explained that [here](https://github.com/chandu0101/sri/issues/19#issuecomment-160159883).
