### ISSUE TITLE
Add fastOptMobile task

### ISSUE THREAD

**Issue by mariussoutier** [chandu0101/sri#20]
Running `fullOptMobile` is not super fast and also makes debugging a bit harder (due to shortened names). Would it be possible to also provide the fastJS mode, i.e. `fastOptMobile`?

**Comment by chandu0101** [comment]
yeah its pain to debug in prod mode :( , we're blocked on https://github.com/facebook/react-native/issues/465

**Comment by mariussoutier** [comment]
Ah too bad.

**Comment by mariussoutier** [comment]
Closing this as it's on your task list.
