### ISSUE TITLE
Compatibility problem with React Native 0.26

### ISSUE THREAD

**Issue by nimae** [chandu0101/sri#41]
Hi

First, thank you for this useful project.

There is a problem with React Native version 0.26. Apparently it is a packaging incompatibility, because what React Native 0.26.0 release notes says:

> React API must be now required from `react` package (previously a warning on 0.25)

([https://github.com/facebook/react-native/releases/tag/v0.26.0](https://github.com/facebook/react-native/releases/tag/v0.26.0))

And this is the error message when `react-native run-android` is executed:

> `undefined in not an object (evaluating '$g.React.Component.prototype')`

**Comment by chandu0101** [comment]
Hi,
     current master code already uses `Rect.Component` from react branch , but sangria example using 0.4.0 https://github.com/chandu0101/sri-sangria-example/blob/master/project/Dependencies.scala#L19. 

for now clone sri -> sbt publishLocal -> change sri version in sangria-example to 0.5.0-SNAPSHOT and you're good to go :)

**Comment by nimae** [comment]
Unfortunately the same problem still exists!

**Comment by chandu0101** [comment]
oh you need to update loader.js (https://github.com/chandu0101/sri-sangria-example/blob/master/mobile/src/main/resources/loader.js)too

``` js
global.React = require('react');
global.ReactNative = require('react-native');
global.Relay = require('react-relay');
```

while running example if you get timeout error : https://github.com/facebook/react-native/issues/6830

i'll release 0.5 this weekend :)

**Comment by nimae** [comment]
Yes! It worked. Thanks a lot.
And good news to have release 0.5 :)
