### ISSUE TITLE
Eliminate getTypedConstructor boilerplate

### ISSUE THREAD

**Issue by nafg** [chandu0101/sri#45]
First, create a base trait

``` scala
trait ReactComponentBase {
  type Props
  type State
}
```

then make ReactComponent extend it and fill in type members to its type arguments.

Then you can have

``` scala
def typedConstructor[A](implicit ct: ConstructorTag[A]) = ct.constructor.asInstanceOf[ReactTypedConstructor[P, S]]
```

However I would take it a step further:

``` scala
class ReactFactory[A, P, S](val ctor: js.Dynamic) {
  def typed = ctor.asInstanceOf[ReactTypedConstructor[P, S]]
  def createElement(props: P): ReactElementU[P, S] = ...
  // all the createElement variants
}
object ReactFactory {
  def apply[A <: ReactComponentBase](implicit ct: ConstructorTag[A]) = new ReactFactory[A, A#Props, A#State](ct.constructor)
```

Now you can write `ReactFactory[MyComponent].createElement(...)`

Note: createElement is necessary, we can't just call it `apply` and use function application syntax, since that would get interpreted as filling the implicit parameter list.

Alternatively, createElement etc. could be modified to something like

``` scala
def createElement[A <: ReactComponentBase](props: A#Props, ...)(implicit ct: ConstructorTag[A]) = ...
```

(or take ReactFactory implicitly as a typeclass).

**Comment by chandu0101** [comment]
merged code from @nafg  fork. thank you @nafg  :)
