### ISSUE TITLE
Runtime error on assign a value to an input in a component

### ISSUE THREAD

**Issue by yawaramin** [chandu0101/sri#46]
With the following code:

``` scala
package testinputvalue

import org.scalajs.dom
import scala.scalajs.js
import scala.scalajs.js.annotation.ScalaJSDefined
import sri.core.ElementFactory.{ createElementNoProps, getTypedConstructor }
import sri.core.{ ReactComponent, ReactElement }
import sri.web.ReactDOM
import sri.web.vdom.htmltagsPrefix_<._

@ScalaJSDefined
final class TestInputValue extends ReactComponent[Unit, Unit] {
  override def render: ReactElement = <.input(value = "foo")
}

object Main extends js.JSApp {
  override def main(): Unit =
    ReactDOM.render(
      createElementNoProps(
        getTypedConstructor(
          js.constructorOf[TestInputValue], classOf[TestInputValue])),

      dom.document getElementById "app")
}
```

and

``` html
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8"><title>Test Input Value</title>
  </head>
  <body>
    <div id="app"></div>

    <script src="https://unpkg.com/react@15.3.1/dist/react.js"></script>
    <script src="https://unpkg.com/react-dom@15.3.1/dist/react-dom.js">
    </script>

    <script
      type="text/javascript"
      src="./target/scala-2.11/dashboard-fastopt.js">
    </script>

    <script type="text/javascript">testinputvalue.Main().main();</script>
  </body>
</html>
```

I'm getting the following runtime error: `Uncaught TypeError: Cannot call isInstance() on a Class representing a raw JS trait/object, scalajsenv.js:208`

I tracked down that exception to https://github.com/scala-js/scala-js/commit/f369c6baac0f568fff511be311c33835d0c021e2 so it looks like Sri is trying to runtime cast my string `foo` to an `UndefOr[String | Int | Double]` and this is throwing the exception ... but beyond that I am confused.

**Comment by nafg** [comment]
Yeah, the vdom's value attribute is broken. For more the workaround is to
use extraAttributes.

**Comment by yawaramin** [comment]
@nafg thanks for the info. I'm now doing `<.input(extraAttributes = js.Dynamic.literal(value = "foo"))` ... is there a better way?

**Comment by nafg** [comment]
Contribute a fix :)
What I would do is make the value parameter an ADT, and in the
implementation convert it to a js.|.

Note that the fix would need to go
https://github.com/chandu0101/sri-dom-generator, and then that would be
used to generate the code in Sri.

(I think ideally the implementations would not be in the Sri codebase, but
would be generated at build time.)

**Comment by chandu0101** [comment]
fix is in master now :)
