### ISSUE TITLE
How to use custom component inside other

### ISSUE THREAD

**Issue by geek29** [chandu0101/sri#47]
I am new to React as well as Sri and Scalajs. I am backend developer working on scala and trying to write app using scala and Sri. I am not able to figure out how to use custom component inside root component See snippet below. Counter is my custom component. I am returning array of View and Counter in render method. I tried putting Counter at leaf level as well inside outermost View.

So how do i use custom comonent?

```
object HelloSriMobile {

  @ScalaJSDefined
  class Component extends ReactComponent[Unit, Unit] {
    def render() = {
      Array(View(style = styles.container)(
        Text(style = styles.text)(s"Welcome to Sri Mobile(${ReactNative.Platform.OS})"),
        Image(style = styles.image, source = ImageSource(uri = "http://www.scala-js.org/images/scala-js-logo-256.png"))(),
        Text(style = styles.text)("Scala.js - Future of app development!")
      ),
      Counter())
    }
  }
```

Code for Counter.scala

```
@ScalaJSDefined
class Counter extends ReactComponent[Props,State] {

  def border = {
    val borderStl = if(state.showBorder) "dashed" else "dotted"
    style(borderWidth := 1, borderStyle := borderStl , padding := 5)
  }

  initialState(State())

  def render() = {
    TouchableWithoutFeedback(style = border)(
      ///iew(onClick = tick _)(s"Clicks: ${state.count}")
      View(style = styles.container)(
        View(style = border)(
          Text(style = styles.text2)("Dashed border style")
        )
      )
    )
  }

  def tick():  Unit = {
    setState(state.copy(count = state.count + 1, showBorder = (!showBorder)))
  }

}
case class Props(initialCount: Int = 0)
case class State(count: Int = 0, showBorder: Boolean = true)

object Counter {
  def apply() = {
    new Counter()
  }
}
```

**Comment by geek29** [comment]
OK I read through the wiki docs and added code below and its working now.. Can you let me know if its correct way to implement companion method : 

```
object Counter {

  def apply () = {
    val ctor = getTypedConstructor(js.constructorOf[Counter],classOf[Counter])
    createElementNoProps(ctor)
  }

}
```

**Comment by chandu0101** [comment]
@geek29 

sorry for **long** delay ,  i believe you don't need this any more! , anyway yes you're right get the ctor  and pass it element factory methods. now sri has better factory methods to create elements, check out 
https://github.com/chandu0101/sri/blob/master/core/src/main/scala/sri/core/ElementFactory.scala#L66

In your example 

``` scala

case class Props(initialCount: Int = 0)
case class State(count: Int = 0, showBorder: Boolean = true)

@ScalaJSDefined
class Counter extends ReactComponent[Props,State] {

  def border = {
    val borderStl = if(state.showBorder) "dashed" else "dotted"
    style(borderWidth := 1, borderStyle := borderStl , padding := 5)
  }
  initialState(State())
  def render() = {
    TouchableWithoutFeedback(style = border)(
      ///iew(onClick = tick _)(s"Clicks: ${state.count}")
      View(style = styles.container)(
        View(style = border)(
          Text(style = styles.text2)("Dashed border style")
        )
      )
    )
  }

  def tick():  Unit = {
    setState(state.copy(count = state.count + 1, showBorder = (!showBorder)))
  }

}
object Counter {
  def apply() = makeElement[Component]
}
```

you can find more examples in web-examples/mobile-examples module. :)

**Comment by nafg** [comment]
@chandu0101 with the new factory there's no need for the singleton and
apply methods, you can have a top-level class called Counter and use
makeElement at the call site

**Comment by chandu0101** [comment]
> there's no need for the singleton and
> apply methods

yeah, but its more readable with singletons isn't it ? 

`makeElement[Counter] vs Counter()`

`makeElementNoPropsWithChildren[Counter]()(children) vs Counter(children)`

**Comment by nafg** [comment]
First of all, that's a choice users should make.
But if you want to encourage it, it would be more idiomatic to have top
level companions.

**Comment by chandu0101** [comment]
> First of all, that's a choice users should make.

agree

> But if you want to encourage it, it would be more idiomatic to have top
> level companions

i feel like naming `Component` is more relevant in `React` context!

**_Edit:**_ yeah i am wrong `Component` extends `ReactComponent` doesn't make much sense!, i'll update the documentation thank you :) 

**_Edit2:**_ hmm nah, when Component has Props/State/styles/etc , defining them in companion object  and importing them to use inside class looks little odd! ,I still believe having a singleton is best option!. anyway its matter of style users can choose whatever they want :)
