### ISSUE TITLE
project name space

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [chandu0101/sri#50]
is seems this project is mature enough to warrant own "proper" name space

please consider a move to a separate git organisation, i.e. `scalajs-sri`
https://github.com/scalajs-sri

as well as changing maven artifacts group name

thank you

**Comment by chandu0101** [comment]
@Andrei-Pozolotin  thanks for bringing it up, definitely sri will be moved to a separate organization, but before that i want to finish the following ..
- update web-router
- more/better documentation
- update mobile-router to use NavigationExperimental instead of Navigator 
- more tests

**Comment by Andrei-Pozolotin** [comment]
great. please accept my invitation to take ownership of https://github.com/orgs/scalajs-sri/ or let me delete that organization if you do not like the name

**Comment by chandu0101** [comment]
> let me delete that organization if you do not like the name

yeah we should come up with a better name(SEO friendly and relevant to tech) for this project :)

**Comment by Andrei-Pozolotin** [comment]
removed

**Comment by chandu0101** [comment]
@Andrei-Pozolotin  https://github.com/chandu0101/sri/issues/55
